class Producto {
  constructor(id, titulo, imagen, precio, autor, categoria, isbn, cantidad, sinopsis, popular) {
    this.id = id;
    this.titulo = titulo;
    this.imagen = imagen;
    this.precio = precio;
    this.autor = autor;
    this.categoria = categoria;
    this.isbn = isbn;
    this.cantidad = cantidad;
    this.sinopsis = sinopsis;
    this.popular = popular;
  }
};

export const productos = [
  new Producto(1, 'La Biblioteca de la Medianoche', 'BibliotecadelaMedianoche.jpg', 28600, 'HAIG, MATT', 'fantasía', 9789878977096, 1, '«entre la vida y la muerte hay una biblioteca. y los estantes de esa biblioteca son infinitos.\nCada libro da la oportunidad de probar otra vida que podrías haber vivido y de comprobar cómo habrían cambiado las cosas si hubieras tomado otras decisiones...\n¿Habrías hecho algo de manera diferente si hubieras tenido la oportunidad?». Nora Seed aparece, sin saber cómo, en la biblioteca de la medianoche, donde se le ofrece una nueva oportunidad para hacer las cosas bien.\nHasta ese momento, su vida ha estado marcada por la infelicidad y el arrepentimiento. Nora siente que ha defraudado a todos, y también a ella misma. Pero esto está a punto de cambiar.\nLos libros de la biblioteca de la medianoche permitirán a Nora vivir como si hubiera hecho las cosas de otra manera. Con la ayuda de una vieja amiga, tendrá la opción de esquivar todo aquello que se arrepiente de haber hecho o no haber hecho, en pos de la vida perfecta.\nPero las cosas no siempre serán como imaginó que serían, y pronto sus decisiones enfrentarán a la biblioteca y a ella misma en un peligro extremo. Nora deberá responder una última pregunta antes de que el tiempo se agote: ¿cuál es la mejor manera de vivir?','si'), 
  new Producto(2, 'Proyecto Hail Mary', 'ProyectoHeilMary.jpg', 35899, 'WEIR, ANDY', 'ciencia ficcion',  9789878977096, 1, 'Ryland Grace es el único superviviente en una misión desesperada. Es la última oportunidad y, si fracasa, la humanidad y la Tierra misma perecerán.\nClaro que, de momento, él no lo sabe. Ni siquiera puede recordar su propio nombre, y mucho menos la naturaleza de su misión o cómo llevarla a cabo.\nLo único que sabe es que ha estado en coma inducido durante mucho mucho tiempo. Acaba de despertar y se encuentra a millones de kilómetros de su hogar, sin más compañía que la de dos cadáveres.\nMuertos sus compañeros de tripulación, y a medida que va recuperando confusamente los recuerdos, Grace se da cuenta de que se enfrenta a una misión imposible.\nRecorriendo el espacio en una pequeña nave, depende de él acabar con una amenaza de extinción para nuestra especie. Sin apenas tiempo y con el ser humano más cercano a años luz de distancia, habrá de conseguirlo estando completamente solo. ¿O no?\nProyecto Hail Mary, una aventura interestelar irresistible como solo Andy Weir podía imaginar, es una historia de descubrimiento, especulación y supervivencia a la altura de El marciano, que nos lleva a lugares que nunca soñamos alcanzar.','si' ),
  new Producto(3, 'Viento y Verdad', 'vientoyverdad.webp', 32900, 'Sanderson, Brandon', 'fantasía', 9878977096, 1, 'La esperada y explosiva conclusión del primer arco de El Archivo de las Tormentas, la emblemática obra maestra de la fantasía épica de Brandon Sanderson, con más de diez millones de lectores en todo el mundo.\nDalinar Kholin desafió al malvado dios Odium a un duelo de campeones en el que se decidirá el futuro de Roshar. Los Caballeros Radiantes solo tienen diez días para prepararse... y la repentina ascensión del taimado e implacable Taravangian al puesto de Odium lo ha sumido todo en una tremenda confusión.\nLa lucha desesperada prosigue simultáneamente a lo largo y ancho del mundo: Adolin en Azimir, Sigzil y Venli en las Llanuras Quebradas y Jasnah en Ciudad Thaylen.\nEl exasesino Seth deberá purgar Shinovar, su tierra natal, de la oscura influencia de los Deshechos. Lo acompaña Kaladin, que afronta una nueva batalla ayudando a Seth a combatir sus propios demonios... y tendrá que hacer lo mismo con Ishar, el demente Heraldo del Todopoderoso.\nAl mismo tiempo, Shallan, Renarin y Rlain se esfuerzan en desentrañar el misterio que hay tras la Deshecha Ba-Ado-Mishram, el de qué papel tuvo en la esclavización de la especie cantora y en el hecho de que los antiguos Caballeros Radiantes mataran a sus spren.\nY Dalinar y Navani buscan una ventaja contra el campeón de Odium que solo puede hallarse en el Reino Espiritual, donde el recuerdo y la posibilidad se combinan en el caos. El destino de todo el Cosmere pende de un hilo.','si'),

  new Producto(4, 'Mañana, mañana y mañana', 'Mañana.jpg', 28600, 'HAIG, MATT', 'romance', 9789878977096, 1, 'e','si'),
  new Producto(5, 'El Resplandor', 'resplandor.jpg', 28000, 'Stephen King', 'terror', 9780307743657, 1, 'La historia de Jack Torrance, un escritor que acepta un trabajo como cuidador de invierno en el aislado Hotel Overlook, donde fuerzas sobrenaturales amenazan su cordura y la seguridad de su familia.', 'si'),
  
  new Producto(6, 'Canción de Navidad', 'cuento1.webp', 12900, 'Charles Dickens', 'cuento', 9788408292074, 1, 'Ebenezer Scrooge es un hombre avaro y egoísta, sarcástico y huraño con sus pocos seres allegados.\nLa víspera de Navidad, el fantasma de su antiguo socio Jacob Marley se le manifiesta, provocando una serie de apariciones de los fantasmas de las Navidades pasadas, presentes y futuras, que despertarán emociones en el protagonista que parecían olvidadas.','no'), 

  new Producto(7, 'El Club de la Navidad', 'cuento3.webp', 12900, 'Becca Freeman', 'cuento', 9788466379144, 1, 'La Navidad es una época para pasar en familia, pero ¿y si tienes que elegir la tuya?\nUna comedia romántica sobre cuatro amigos que tratan de aferrarse a su propia tradición navideña en la ciudad de Nueva York, perfecta para los fans de Gente que conocemos de vacaciones y Un día de diciembre.\nDurante diez años, Hannah y Finn han pasado las navidades juntos. Al no tener a nadie con quien compartirlas (los padres de Hannah murieron y los de Finn lo desheredaron cuando salió del armario), han creado sus propias tradiciones: desgañitarse en un karaoke detrás de un restaurante de Chinatown, saludar desde la carroza de un desfile, patinar sobre hielo bajo el árbol del Rockefeller Center...\nA lo largo de los años, se les han unido la moderna Priya y el misterioso Theo, y juntos han creado el Club de la Navidad.\nSin embargo, todo está a punto de cambiar para siempre. Finn tiene una noticia que hace que los cimientos del grupo se tambaleen: esta Navidad podría ser la última que compartan.\nA Hannah le aterroriza perder la familia que tanto le ha costado encontrar, y a Finn, enfrentarse a todo lo que va a dejar atrás... Concretamente, a lo que siente por Theo.\nSin embargo, avanzar no siempre implica distanciarse y puede que, estas navidades, los cambios que tanto temen sean precisamente los que más necesitan.','no'), 

  new Producto(8, 'Cumbres Borrascosas', 'cumbre.jpg', 24000, 'Emily Brontë', 'romance', 9780141439556, 1, 'Una apasionada historia de amor y venganza entre Heathcliff y Catherine Earnshaw, ambientada en los páramos de Yorkshire.', 'si'),

  new Producto(9, 'Cuentos de Navidad', 'cuento2.webp', 12900, 'Charles Dickens', 'cuento', 9788408292074, 1, 'Ebenezer Scrooge es un hombre avaro y egoísta, sarcástico y huraño con sus pocos seres allegados.\nLa víspera de Navidad, el fantasma de su antiguo socio Jacob Marley se le manifiesta, provocando una serie de apariciones de los fantasmas de las Navidades pasadas, presentes y futuras, que despertarán emociones en el protagonista que parecían olvidadas.','no'), 

  new Producto(10, 'El Alquimista', 'alquimista.jpg', 25000, 'Paulo Coelho', 'ficción', 9780061122415, 1, 'La historia de Santiago, un joven pastor andaluz que viaja desde su tierra natal en España hasta el desierto egipcio en busca de un tesoro escondido en las pirámides. Lo que comienza como la búsqueda de bienes mundanos se convierte en la búsqueda de un tesoro más valioso: el descubrimiento de uno mismo.', 'si'), 

  new Producto(11, 'Drácula', 'dracula.jpg', 26000, 'Bram Stoker', 'terror', 9780141439846, 1, 'La clásica novela de terror que narra la lucha del joven abogado Jonathan Harker y sus amigos contra el vampiro Conde Drácula.', 'si'),

  new Producto(12, 'Cien Años de Soledad', 'soledad.jpg', 32000, 'Gabriel García Márquez', 'realismo mágico', 9780307474728, 1, 'La historia épica de la familia Buendía en el pueblo ficticio de Macondo, que abarca varias generaciones y explora temas de amor, soledad, y el paso del tiempo.', 'si'), 

  new Producto(13, '1984', '1984.jpg', 28000, 'George Orwell', 'distopía', 9780451524935, 1, 'Una novela distópica que presenta una sociedad totalitaria bajo el control del Gran Hermano, donde la vigilancia y la represión son omnipresentes. La historia sigue a Winston Smith, un hombre que comienza a cuestionar el régimen opresivo en el que vive.', 'si'), 

  new Producto(14, 'El Principito', 'principito.jpg', 15000, 'Antoine de Saint-Exupéry', 'fábula', 9780156012195, 1, 'Un piloto varado en el desierto del Sahara conoce a un joven príncipe que ha viajado desde un pequeño planeta. A través de sus conversaciones, el piloto aprende sobre el amor, la pérdida y la importancia de ver con el corazón.', 'si') ,
  
  new Producto(15, 'Orgullo y Prejuicio', 'orgullo.jpg', 22000, 'Jane Austen', 'romance', 9780141040349, 1, 'La historia de Elizabeth Bennet y su complicada relación con el orgulloso Sr. Darcy, en una novela que explora temas de amor, clase social y prejuicio.', 'si')
];

